### ISSUE TITLE
Should be able to "follow" a user

### ISSUE THREAD

**Issue by charlieroberts** [steinfernandez/gibber-frontend-react#12]
Any user A should be able to follow a user B. User A will then receive notifications (in the feed) when user B publishes a new giblet, or is online at the same time as user A (for chatting). User A should be able to unfollow user B. 

User A should also be able to collectively follow all the members of a given group. This could be implemented by having a "select all" button when viewing a group and also providing follow/unfollow buttons.

**Comment by charlieroberts** [comment]
change: users should only be notified when *friends* are online, not people they follow.

**Comment by steinfernandez** [comment]
implemented.
