### ISSUE TITLE
Users should be able to "like" giblets 

### ISSUE THREAD

**Issue by charlieroberts** [steinfernandez/gibber-frontend-react#13]
Any user who is logged in should be able to "like" another user's giblets. This could be a simple heart button present in the tab bar that also displays the current like count (similar to how it appears in the semantic-ui feed demo). Users should also be able to view all the people that have liked their giblet in the meta info / editing page for each giblet.

**Comment by steinfernandez** [comment]
Liking and unliking should be fully functional now.

**Comment by steinfernandez** [comment]
Users that liked a giblet are shown in the edit metadata modal, under a disabled page. This should likely be changed or styled to accommodate larger numbers, however.

**Comment by steinfernandez** [comment]
Shifted user list to right side of form and displayed horizontally.
