### ISSUE TITLE
When page is refreshed, user appears to no longer be logged in but files are still visible.

### ISSUE THREAD

**Issue by steinfernandez** [steinfernandez/gibber-frontend-react#14]

**Comment by charlieroberts** [comment]
Just to be clear, there are two problems here.

1. If the user is logged out, their files shouldn't be visible.
2. When the page is refreshed, the user should *not* be logged out. So, in practice, when the page is refreshed their files will actually still be visible (and their name should appear next to the login button etc.).

**Comment by steinfernandez** [comment]
Logging out now clears most redux store data. Breadcrumbs and tabs are preserved.

**Comment by charlieroberts** [comment]
In looking at current gibber, you just need to do a check to see if a user is logged in whenever a page is refreshed.

**Comment by steinfernandez** [comment]
fixed.
