### ISSUE TITLE
Enable "forking" of giblets

### ISSUE THREAD

**Issue by charlieroberts** [steinfernandez/gibber-frontend-react#16]
When a user "forks" a giblet, the following happens:

1. The user is prompted to rename the giblet. If they are forking another user's giblet then no renaming is necessary; otherwise they are required to name it something different. If a user forks their own giblet it, in effect, simply creates a copy of it with a different name

2. The metadata of the giblet includes a reference to the original source of the fork, including the a link to the profile of the original author.

In a similar vein to "likes" we could also display a button showing the number of times a giblet has been "forked", a la https://semantic-ui.com/elements/button.html in the "Labeled" section.

**Comment by steinfernandez** [comment]
Giblets can be forked. Default names are supplied as appropriate, but the user has the option to change the default before forking. Metadata containing original file name and author is added.

**Comment by steinfernandez** [comment]
Number of forks are now tracked. Labeled buttons look completely broken (visually, perhaps a css issue?) for some reason, so currently just displaying a number next to the button.
