### ISSUE TITLE
EditMetadata doesn't work.

### ISSUE THREAD

**Issue by steinfernandez** [steinfernandez/gibber-frontend-react#4]

**Comment by charlieroberts** [comment]
should this be in the server repo?

**Comment by steinfernandez** [comment]
Edited. Is caused bya bad request due to restructuring of the redux store done while fixing another bug earlier. I think perhaps I should open separate issues in the server repo to include try/catch statements where I haven't already.

**Comment by steinfernandez** [comment]
Fixed.
