### ISSUE TITLE
place save button in tab (next to close button)

### ISSUE THREAD

**Issue by charlieroberts** [steinfernandez/gibber-frontend-react#5]
We want to save as much vertical real estate as possible for the code editors. Putting the disk icon in the tab header would save a bunch. You can just launch a popup requesting login if they try to save without logging in first.

**Comment by steinfernandez** [comment]
1. Wouldn't it look cramped? 
2. What about the edit metadata button next to it?

**Comment by charlieroberts** [comment]
The tab headers can just be bigger horizontally to fit extra buttons... it's the vertical real estate I'm mainly worried about.

**Comment by charlieroberts** [comment]
OK, changed my mind on this one. After working on the stylesheet the vertical space isn't as much of an issue to me.
